02hello2app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.hello)
]

21bbs/apps/cms/forms.py
from wtforms import Form, StringField, IntegerField, ValidationError
from wtforms.validators import Email, InputRequired, Length, EqualTo
from apps.forms import BaseForm
from utils import cache
from flask import g

class LoginForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确的邮箱格式'), InputRequired(message='请输入邮箱')])
    password = StringField(validators=[Length(3, 20, message='密码长度3到20位')])
    remember = IntegerField()

class ResetpwdForm(BaseForm):
    oldpwd = StringField(validators=[Length(3, 20, message='密码长度3到20位')])
    newpwd = StringField(validators=[Length(3, 20, message='密码长度3到20位')])
    newpwd2 = StringField(validators=[EqualTo('newpwd', message='必须与新密码保持一致')])

class ResetEmailForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确格式的邮箱')])
    captcha = StringField(validators=[Length(6, 6, message="请输入6位验证码")])

    def validate_captcha(self, field):
        captcha = field.data
        email = self.email.data
        captcha_cache = cache.get(email)
        if not captcha_cache or captcha.lower() != captcha_cache.lower():
            raise ValidationError('邮箱验证码错误')

    def validate_email(self, field):
        email = field.data
        user = g.cms_user
        if user.email == email:
            raise ValidationError('不能修改为相同的邮箱')

class AddBannerForm(BaseForm):
    name = StringField(validators=[InputRequired(message='请输入轮播图名称')])
    image_url = StringField(validators=[InputRequired(message='请输入轮播图链接')])
    link_url = StringField(validators=[InputRequired(message='请输入轮播图跳转链接')])
    priority = IntegerField(validators=[InputRequired(message='请输入轮播图优先级')])

class UpdateBannerForm(AddBannerForm):
    banner_id = IntegerField(validators=[InputRequired(message='请输入轮播图的id')])

class AddBoardForm(BaseForm):
    name = StringField(validators=[InputRequired(message='请输入板块名称')])

class UpdateBoard(AddBoardForm):
    board_id = IntegerField(validators=[InputRequired(message='请输入板块id')])

21bbs/apps/forms.py
from flask_wtf import Form

class BaseForm(Form):
    def get_error(self):
        message = self.errors.popitem()[1][0]
        return message

21_bbs_exercise/apps/front/views.py
from flask import Blueprint, views, render_template, make_response
from utils.captcha import Captcha
from io import BytesIO

bp = Blueprint("front", __name__)

@bp.route('/')
def index():
    return 'front_index'

class SignupView(views.MethodView):
    def get(self):
        return render_template('front/front_signup.html')

bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))

@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp

21bbs/apps/cms/views.py
from flask import Blueprint, views, render_template, request, session, redirect, url_for, g, jsonify
from .forms import LoginForm, ResetpwdForm, ResetEmailForm, AddBannerForm, UpdateBannerForm, AddBoardForm, UpdateBoard
from .models import CMSUser, CMSPermission
from .decorators import login_required, permission_required
import config
from exts import db, mail
from flask_mail import Message
from utils import restful
import string
import random
from utils import cache
from ..models import BannerModel, BoardModel, HighlightPostModel, PostModel

bp = Blueprint("cms", __name__, url_prefix='/cms')

@bp.route('/')
@login_required  # 限制cms登录
def index():
    return render_template('cms/cms_index.html')

@bp.route('/logout/')
@login_required
def logout():
    session.clear()
    return redirect(url_for('cms.login'))

@bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/cms_profile.html')

@bp.route('/email_captcha/')
def email_captcha():
#      /email_captcha/?email=xxx@qq.com
    email = request.args.get('email')
    if not email:
        return restful.paramserror('请传递邮箱参数')
#     给这个邮箱发送邮件
    source = list(string.ascii_letters)
    source.extend(map(lambda x: str(x), range(0, 10)))
    captcha = "".join(random.sample(source, 6))
    message = Message('python论坛', recipients=[email], body='您的验证码是%s' % captcha)
    try:
        mail.send(message)
    except:
        return restful.servererror()

    cache.set(email, captcha)
    return restful.success()
# 邮箱测试代码
# @bp.route('/email/')
# def send_email():
#     message = Message('邮件发送', recipients=['1194684253@qq.com'], body='测试')
#     mail.send(message)
#     return 'success'

class LoginView(views.MethodView):

    def get(self, message=None):
        return render_template("cms/cms_login.html", message=message)
    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = CMSUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID] = user.id
                if remember:
                    # 设置为true，默认保存31天
                    session.permanent = True
                return redirect(url_for('cms.index'))
            else:
                return self.get(message='邮箱或密码错误')
        else:
            message = form.get_error()  # apps.forms中BaswForm将error函数抽象出来
            return self.get(message=message)

bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))

class ResetPwdView(views.MethodView):
    decorators = [login_required]
    def get(self):
        return render_template('cms/cms_resetpwd.html')
    def post(self):
        form = ResetpwdForm(request.form)
        if form.validate():
            newpwd = form.newpwd.data
            oldpwd = form.oldpwd.data
            user = g.cms_user
            if user.check_password(oldpwd):
                user.password = newpwd
                db.session.commit()
                return restful.success()   # utils.py中restful定义的http状态
            else:
                return restful.paramserror('旧密码错误')
        else:
            return restful.paramserror(form.get_error())

bp.add_url_rule('/resetpwd/', view_func=ResetPwdView.as_view('resetpwd'))

class ResetEmailView(views.MethodView):
    decorators = [login_required]
    def get(self):
        return render_template('cms/cms_resetemail.html')
    def post(self):
        form = ResetEmailForm(request.form)
        if form.validate():
            email = form.email.data
            g.cms_user.email = email
            db.session.commit()
            return restful.success()
        else:
            return restful.paramserror(form.get_error())

bp.add_url_rule('/resetemail/', view_func=ResetEmailView.as_view('resetemail'))

@bp.route('/posts/')
@login_required
@permission_required(CMSPermission.POSTER)
def posts():
    context = {
        'posts': PostModel.query.all()
    }
    return render_template('cms/cms_posts.html', **context)

@bp.route('/hpost/', methods=['POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def hpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.paramserror('请传入帖子id')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.paramserror('没有这篇帖子')
    highlight = HighlightPostModel()
    highlight.post = post
    db.session.add(highlight)
    db.session.commit()
    return restful.success()

@bp.route('/uhpost/', methods=['POST'])
@login_required
@permission_required(CMSPermission.POSTER)
def uhpost():
    post_id = request.form.get('post_id')
    if not post_id:
        return restful.paramserror('请传入帖子id')
    post = PostModel.query.get(post_id)
    if not post:
        return restful.paramserror('没有这篇帖子')
    highlight = HighlightPostModel.query.filter_by(post_id=post_id).first()
    db.session.delete(highlight)
    db.session.commit()
    return restful.success()


@bp.route('/comments/')
@login_required
@permission_required(CMSPermission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')

@bp.route('/boards/')
@login_required
@permission_required(CMSPermission.BOARDER)
def boards():
    board_models = BoardModel.query.all()
    context = {
        'boards': board_models
    }
    return render_template('cms/cms_boards.html', **context)

@bp.route('/aboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.paramserror(form.get_error())

@bp.route('/uboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def uboard():
    form = UpdateBoard(request.form)
    if form.validate():
        board_id = form.board_id.data
        name = form.name.data
        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return restful.success()
        else:
            return restful.paramserror(message='没有这个版块')
    else:
        return restful.paramserror(form.get_error())


@bp.route('/dboard/', methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def dboard():
    board_id = request.form.get('board_id')
    if not board_id:
        return restful.paramserror('请传入板块id')
    board = BoardModel.query.get(board_id)
    if not board:
        return restful.paramserror('没有这个板块')
    db.session.delete(board)
    db.session.commit()
    return restful.success()

@bp.route('/fusers/')
@login_required
@permission_required(CMSPermission.FRONTUSER)
def fusers():
    return render_template('cms/cms_fusers.html')

@bp.route('/cusers/')
@login_required
@permission_required(CMSPermission.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')

@bp.route('/croles/')
@login_required
@permission_required(CMSPermission.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')

@bp.route('/banners/')
@login_required
def banners():
    banners = BannerModel.query.all()
    return render_template('cms/cms_banners.html', banners= banners)

@bp.route('/abanner/', methods=['POST'])
@login_required
def abanner():
    form = AddBannerForm(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name, image_url=image_url, link_url=link_url, priority=priority)
        db.session.add(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.paramserror(message=form.get_error())


@bp.route('/ubanner/', methods=['POST'])
@login_required
def ubanner():
    form = UpdateBannerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            db.session.commit()
            return restful.success()
        else:
            return restful.paramserror(message='没有这个轮播图')
    else:
        return restful.paramserror(form.get_error())


@bp.route('/dbanner/', methods=['POST'])
@login_required
def dbanner():
    banner_id = request.form.get('banner_id')
    print(banner_id)
    if not banner_id:
        return restful.paramserror(message='请传入轮播图id')

    banner = BannerModel.query.get(banner_id)
    if not banner:
        return restful.paramserror(message='没有这个轮播图')
    db.session.delete(banner)
    db.session.commit()
    return restful.success()

21bbs/apps/common/views.py
from flask import Blueprint

bp = Blueprint("common", __name__, url_prefix='/common')

@bp.route('/')
def index():
    return 'common_index'

21bbs/apps/front/views.py
from flask import Blueprint, views, render_template, make_response, request, session, url_for, g, abort
from utils.captcha import Captcha
from io import BytesIO
from .forms import SigninForm, AddPostForm, AddCommentForm
from .models import FrontUser
import config
from utils import restful
from apps.models import BoardModel, PostModel, CommentModel,HighlightPostModel
from .decorators import login_required
from exts import db
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy.sql import func

bp = Blueprint("front", __name__)

@bp.route('/')
def index():
    board_id = request.args.get('bd', type=int, default=None)
    sort = request.args.get('st', type=int, default=1)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    boards = BoardModel.query.all()
    start = (page-1)*config.PER_PAGE
    end = start+config.PER_PAGE
    posts = None
    total = 0

    query_obj = None
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 加精的时间倒叙排列
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
    #     按照点赞的顺序  （点赞没做）
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
    #     按照评论数量
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(func.count(CommentModel.id).desc(), PostModel.create_time.desc())
    if board_id:
        posts = query_obj.filter(PostModel.board_id == board_id).slice(start, end)
        total = query_obj.filter(PostModel.board_id==board_id).count()
    else:
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    pagination = Pagination(bs_version=3, page=page, total=total)
    context = {
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort': sort
    }
    return render_template('front/front_index.html', **context)

@bp.route('/p/<post_id>')
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html', post=post)

@bp.route('/acomment/', methods=['POST'])
@login_required
def add_comment():
    form = AddCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        post = PostModel.query.get(post_id)
        if post:
            comment = CommentModel(content=content)
            comment.post = post
            comment.author = g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.paramserror(message='没有这个帖子')
    else:
        return restful.paramserror(form.get_error())


class SignupView(views.MethodView):
    def get(self):
        return render_template('front/front_signup.html')

bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))

@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        context = {
            'boards': boards
        }
        return render_template('front/front_apost.html', **context)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.paramserror(message='没有这个板块')
            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.paramserror(form.get_error())


@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    out = BytesIO()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp


class SigninView(views.MethodView):
    def get(self):
        return_to = request.referrer
        if return_to and return_to!= request.url and return_to!=url_for('front.signup'):
            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data
            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.paramserror(message='手机号码或密码错误')
        return restful.paramserror(message=form.get_error())

bp.add_url_rule('/signin/', view_func=SigninView.as_view('signin'))

21bbs/templates/front/front_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404</title>
</head>
<body>
    您要找的页面已经到火星去了
    <div>
        <a href="/">回到首页</a>
    </div>
</body>
</html>

21bbs/templates/front/front_apost.html
{% extends 'front/front_base.html' %}
{% from 'common/_macro.html' import static %}

{% block title %}
        发布帖子
{% endblock %}
{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static('front/js/front_apost.js') }}"></script>
    <link rel="stylesheet" href="{{ static('common/sweetalert/sweetalert.css')}}">
{% endblock %}
{% block body %}
    <form action="" method="post">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">标题</span>
                <input type="text" name="title" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">板块</span>
                <select name="board_id" class="form-control">
                    {% for board in boards %}
                        <option value="{{ board.id }}">{{ board.name }}</option>
                    {% endfor %}

                </select>
            </div>
        </div>
        <div class="form-group">
            <script id="editor" type="text/plain" style="height: 500px;"></script>
        </div>
        <div class="form-group">
            <button class="btn btn-danger" id="submit-btn">发布帖子</button>
        </div>
    </form>
{% endblock %}

21bbs/templates/front/front_base.html
{%  include'common/_headers.html' %}
{% from 'common/_macro.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ static('front/css/front_base.css') }}">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">python论坛</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class=""><a href="#">首页<span class="sr-only">(current)</span></a></li>

              </ul>
              <form class="navbar-form navbar-left">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="请输入关键字">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
              </form>
              <ul class="nav navbar-nav navbar-right">
              <span id="login-tag" data-is-login='1' style="display: none"></span>
                {% if g.front_user %}
                    <li class="dropdown">
                      <a href="#" class=" dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {{ g.front_user.username }}
                        <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="#">个人中心</a></li>
                        <li><a href="#">设置</a></li>
                        <li><a href="#">注销</a></li>
                      </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for('front.signin') }}">登录</a></li>
                    <li><a href="{{ url_for('front.signup') }}">注册</a></li>
                {% endif %}


              </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="main-container">
        {% block body %}{% endblock %}
    </div>
</body>
</html>

21bbs/templates/front/front_index.html
{% extends 'front/front_base.html' %}
{% block title %}
    python论坛
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ static('front/css/front_index.css') }}">
{% endblock %}
{% block body %}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
  <!-- Indicators -->
         <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
          </ol>
        
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
              <div class="item active">
                <a href="#">
                    <img src="https://static.bootcss.com/www/assets/img/luffycity.png" alt="...">
                </a>
              <div class="carousel-caption">
                ...
              </div>
            </div><div class="item">
                <a href="#">
                    <img src="https://static.bootcss.com/www/assets/img/react.png?1519784809415" alt="...">
                </a>
              <div class="carousel-caption">
                ...
              </div>
            </div>
            <div class="item">
                <a href="#">
                    <img src="https://static.bootcss.com/www/assets/img/codeguide.png?1519784809415" alt="...">
                </a>
              <div class="carousel-caption">
                ...
              </div>
            </div>
            <div class="item">
              <a href="#">
                    <img src="https://static.bootcss.com/www/assets/img/typescript.png?1519784809415" alt="...">
                </a>
              <div class="carousel-caption">
                ...
              </div>
            </div>
            ...
          </div>
        
          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <div class="post-group">
            <ul class="post-group-head">
                <li><a href="{{ url_for('front.index', st=1, bd=current_board) }}">最新</a></li>
                <li><a href="{{ url_for('front.index', st=2, bd=current_board) }}">精华帖子</a></li>
                <li><a href="{{ url_for('front.index', st=3, bd=current_board) }}">点赞最多</a></li>
                <li><a href="{{ url_for('front.index', st=4, bd=current_board) }}">评论最多</a></li>
            </ul>
            <ul class="post-list-group">
                {% for post in posts %}
                    <li style="overflow: hidden;padding-bottom: 30px">
                        <div class="author-avatar-group">
                            <img src="{{ post.author.avatar or url_for('static', filename='common/images/logo.png') }}" alt="">
                        </div>
                    <div class="post-info-group">
                        <p class="post-title"><a href="{{ url_for('front.post_detail', post_id=post.id) }}">{{ post.title }}</a>
                        {% if post.highlight %}
                            <span class="label label-danger" style="margin-left: 20px">精华帖</span>
                        {% endif %}
                        </p>
                        <p class="post-info">
                            <span>作者：{{ post.author.username }}</span>
                            <span>发表时间：{{ post.create_time }}</span>
                            <span>评论数：0</span>
                            <span>阅读数：0</span>
                        </p>
                    </div>
                    </li>
                {% endfor %}

            </ul>
        <div style="text-align:center;">
            {{ pagination.links }}
        </div>
        </div>
    </div>
    <div class="sm-container">
        <div style="padding-bottom: 10px">
            <a href="{{ url_for('front.apost') }}" class="btn btn-warning btn-block">发布帖子</a>
        </div>
        <div class="list-group">
            {% if current_board %}
                <a href="/" class="list-group-item">所有板块</a>
            {% else %}
                 <a href="/" class="list-group-item active">所有板块</a>
                {% endif %}
            {% for board in boards %}
                {% if board.id == current_board %}
                    <a href="{{ url_for('front.index',bd=board.id ) }}" class="list-group-item active">{{ board.name }}</a>
                {% else %}
                    <a href="{{ url_for('front.index',bd=board.id ) }}" class="list-group-item ">{{ board.name }}</a>
                {% endif %}

            {% endfor %}

        </div>
    </div>
{% endblock %}

21bbs/templates/front/front_pdetail.html
{% extends 'front/front_base.html' %}
{% from 'common/_macro.html' import static %}
{% block title %}
    {{ post.title }}
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static('front/css/front_pdetail.css') }}">
        <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <link rel="stylesheet" href="{{ static('common/sweetalert/sweetalert.css')}}">
    <script src="{{ static('front/js/front_pdetail.js') }}"></script>
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div class="post-container">
            <h2>{{ post.title }}</h2>
            <p class="post-info-group">
                <span>发表时间：{{ post.create_time }}</span>
                <span>作者：{{ post.author.username }}</span>
                <span>所属板块：{{ post.board.name }}</span>
                <span>阅读数：{{ post.read_count }}</span>
                <span>评论数：0</span>
            </p>
            <article class="post-content" data-id="{{ post.id }}" id="post-content">
                {{ post.content|safe }}
            </article>
        </div>
        <div class="comment-group">
            <h3>评论列表</h3>
            <ul class="comment-list-group">
                {% for comment in post.comments %}
                    <li>
                    <div class="avatar-group"><img src="{{ comment.author.avatar or static('common/images/logo.png') }}" alt="">
                    </div>
                        <div class="comment-content">
                            <p class="author-info"><span>{{ comment.author.username }}</span></p>
                            <p class="author-info"><span>{{ comment.create_time }}</span></p>
                            <p class="comment-txt">
                                {{ comment.content|safe }}
                            </p>
                        </div>

                    </li>
                {% endfor %}
                
            </ul>
        </div>
    <div class="add-comment-group">
        <h3>发表评论</h3>
        <script id="editor" type="text/plain" style="height: 100px;" ></script>
        <div class="comment-btn-group">
            <button class="btn btn-primary" id='comment-btn'>发表评论</button>
        </div>
    </div>
    </div>
    <div class="sm-container"></div>
{% endblock %}

21bbs/templates/front/front_signup.html
{% extends 'front/front_signbase.html' %}
{% from 'common/_macro.html' import static %}

{% block title %}
    注册页面
{% endblock %}

{% block head %}
    <script src="{{ static('front/js/front_signup.js') }}"></script>
{% endblock %}

{% block h2_block %}
    账号注册
{% endblock %}
{% block sign_box %}
<div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                    <span class="input-group-btn">
                        <button class="btn btn-default">发送验证码</button>
                    </span>
                </div>
            </div>
            <div class="form-group">
                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
            </div>
            <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="用户名">
            </div>
            <div class="form-group">
                    <input type="text" class="form-control" name="password1" placeholder="密码">
            </div>
            <div class="form-group">
                    <input type="text" class="form-control" name="password2" placeholder="确认密码">
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control" name="graph_catcha" placeholder="图形验证码">
                    <span class="input-group-btn captcha-addon">
                        <img id="captcha-img" class='captcha-img' src="{{ url_for('front.graph_captcha') }}" alt="">
                    </span>
                </div>
            </div>
            <div class="form-group">
                <button class="btn btn-warning btn-block" id="submit-btn">注册</button>
            </div>
{% endblock %}